version: '2.3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
        php:
          condition: service_healthy
    environment:
      - ENV=development
  php:
    image: php:7.2-fpm
    volumes:
      - ./src:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 1s
